### ISSUE TITLE
Not working with Launchpad RGB MK2

### ISSUE THREAD

**Issue by dhilowitz** [stevenleeg/launchpadder#7]
Hi, 

I'm trying to get this to work with my Launchpad MK2. When I start up the sample app, everything seem's to work. I press the top-left button and the light goes, but:

1. In the console it says the wrong coordinates.

```
(1, 5) was pressed. 
(1, 5) was released
```
2. The code says that it should be making the pads red, but they are showing up as light yellow.
3. When I press any of the buttons beyond the first two rows, nothing happens and I get errors:

```
app.js:10
    button.light(launchpadColor.RED);
          ^

TypeError: Cannot read property 'light' of undefined
    at Launchpad.<anonymous> (/Users/dhilowitz/Dropbox (Personal)/Projects/Launchpad Projects/dave-launchpad-1/app.js:10:11)
    at emitOne (events.js:96:13)
    at Launchpad.emit (events.js:191:7)
    at NodeMidiInput.<anonymous> (/Users/dhilowitz/Dropbox (Personal)/Projects/Launchpad Projects/dave-launchpad-1/node_modules/launchpadder/launchpadder.js:231:18)
    at emitTwo (events.js:106:13)
    at NodeMidiInput.emit (events.js:194:7)
```

Are these known issues?

**Comment by dhilowitz** [comment]
It seems that the MIDI driver is returning numbers in decimal, but launchpadder expects hex.

**Comment by CrazyH2** [comment]
@JeromSar @stevenleeg @brandly, will you still be working on this? and if so will you be adding support for the launchpad X?
